import java.io.ByteArrayOutputStream;import java.util.*;
/* V2: only the battle native is staged out of SB2, because its task/savedCallback
   must survive CB2_InitBattle -> MoveSaveBlocks_ResetHeap. Field-only helpers
   remain direct persistent calls. No InstallationManifest is involved. */
final class MewPersistentDispatcherNative{
 private MewPersistentDispatcherNative(){}
 static byte[] build(RomProfile rom,int prepare,int launch,int sceneStan,int sceneShane){var b=MewEventDataCore.build(rom);var tx=MewBattleCoreNative.buildAt(rom,0);long stage=rom.stringVar4+0x140L;int[]off={0,0,MewEventDataCore.STORAGE_OFFSET+b.transformRebindOffset(),MewEventDataCore.STORAGE_OFFSET+b.ensureMewOffset(),MewEventDataCore.STORAGE_OFFSET+b.rewardOffset(),sceneStan,sceneShane};T t=new T();t.u16(0xB500);t.ldr(0,"mode");t.u16(0x8800);t.u16(0x2800);t.bc(0,"prepare");t.u16(0x2801);t.bc(0,"launch");
  // modes 2..4 are Event/Data helpers in SB1; modes 5..6 are the exact Probe-6P
  // Stan/Shane helper bytes stored in SB2. V2 Fix1 had these bases reversed for 5/6.
  t.u16(0x2805);t.bc(3,"sb1");t.label("sb2");t.ldr(3,"sb2p");t.b("base");t.label("sb1");t.ldr(3,"sb1p");t.label("base");t.u16(0x681B);t.u16(0x0040);t.adr(1,"table");t.u16(0x1809);t.u16(0x8809);t.u16(0x185B);t.u16(0x3301);t.b("call");
  t.label("prepare");t.ldr(0,"sb2p");t.u16(0x6800);t.ldr(1,"battleSrc");t.u16(0x1840);t.ldr(1,"stage");t.ldr(2,"battleCtl");t.u16(0xDF0B);t.ldr(3,"stageThumb");t.b("call");
  t.label("launch");t.ldr(3,"stage");t.ldr(1,"launchRel");t.u16(0x185B);t.u16(0x3301);
  t.label("call");t.bl("thunk");t.u16(0xBD00);t.label("thunk");t.u16(0x4718);t.align();t.label("table");for(int x:off)t.u16(x);t.align();t.lit("mode",rom.specialVarResult);t.lit("sb1p",rom.saveBlock1Ptr);t.lit("sb2p",rom.saveBlock2Ptr);t.lit("battleSrc",MewBattleCore.STORAGE_OFFSET+MewBattleCore.HEADER_SIZE);t.lit("stage",stage);t.lit("stageThumb",stage|1L);t.lit("battleCtl",0x04000000L+(tx.helper().size()/4));t.lit("launchRel",tx.launchOffset());return t.finish();}
 private static final class T{ByteArrayOutputStream o=new ByteArrayOutputStream();Map<String,Integer>lab=new HashMap<>(),lp=new HashMap<>();List<B>bs=new ArrayList<>();List<BL>bls=new ArrayList<>();List<L>ls=new ArrayList<>(),ads=new ArrayList<>();Map<String,Long>lv=new LinkedHashMap<>();int p(){return o.size();}void u16(int v){o.write(v&255);o.write(v>>>8&255);}void label(String s){lab.put(s,p());}void align(){while((p()&3)!=0)u16(0x46C0);}void bc(int c,String s){int p=p();u16(0xD000|c<<8);bs.add(new B(p,s,false));}void b(String s){int p=p();u16(0xE000);bs.add(new B(p,s,true));}void bl(String s){int p=p();u16(0);u16(0);bls.add(new BL(p,s));}void ldr(int r,String s){int p=p();u16(0x4800|r<<8);ls.add(new L(p,r,s));}void adr(int r,String s){int p=p();u16(0xA000|r<<8);ads.add(new L(p,r,s));}void lit(String s,long v){lv.put(s,v);}byte[]finish(){align();for(var e:lv.entrySet()){lp.put(e.getKey(),p());long v=e.getValue();o.write((int)v&255);o.write((int)(v>>>8)&255);o.write((int)(v>>>16)&255);o.write((int)(v>>>24)&255);}byte[]a=o.toByteArray();for(B f:bs){int h=(lab.get(f.s)-(f.p+4))/2;if(f.un){if(h< -1024||h>1023)throw new IllegalStateException("b");put(a,f.p,0xE000|(h&0x7FF));}else{if(h< -128||h>127)throw new IllegalStateException("bc");int x=(a[f.p]&255)|(a[f.p+1]&255)<<8;put(a,f.p,(x&0xFF00)|(h&255));}}for(BL f:bls){int d=lab.get(f.s)-(f.p+4);put(a,f.p,0xF000|((d>>12)&0x7FF));put(a,f.p+2,0xF800|((d>>1)&0x7FF));}for(L f:ads){int pc=(f.p+4)&~3,d=lab.get(f.s)-pc;if(d<0||(d&3)!=0||d/4>255)throw new IllegalStateException("adr");put(a,f.p,0xA000|f.r<<8|d/4);}for(L f:ls){int pc=(f.p+4)&~3,d=lp.get(f.s)-pc;if(d<0||(d&3)!=0||d/4>255)throw new IllegalStateException("ldr "+f.s);put(a,f.p,0x4800|f.r<<8|d/4);}return a;}static void put(byte[]a,int p,int v){a[p]=(byte)v;a[p+1]=(byte)(v>>>8);}record B(int p,String s,boolean un){}record BL(int p,String s){}record L(int p,int r,String s){} }
}
