final class MewV2CompositionTest { static void run(){var r=RomProfile.FIRE_RED_EN_10;var a=MewBattleCore.build(r);var x=MewBattleCoreExtension.layout(r);var b=MewEventDataCore.build(r);require(a.bytes().length==448,"A base size");require(x.dispatcherOffset()+x.dispatcherBytes().length<=MewBattleCore.SCRATCH_RELATIVE,"A extension before ball scratch");require(b.bytes().length<=MewEventDataCore.CAPACITY,"B fits SB1");require(MewFinalEventPreset.build(r).payloadBytes()<=RamScript.SCRIPT_SIZE,"event fits WC");require((r.stringVar4+0x100L)==CpuSetNativeHelperInstaller.helperDestination(r.stringVar4+0xC0L),"bridge at +0x100");require((r.stringVar4+0x140L)==CpuSetNativeHelperInstaller.helperDestination(r.stringVar4+0x100L),"Probe24 stage at +0x140");byte[] mewCb=new ObjectEventRamScriptBinding(PersistentEventMewRecoveryProbePreset.MEW_HOST).continuationCallback(r,0);require((mewCb[2]&0xFF)==0x0B && (mewCb[3]&0xFF)==0x20,"final battle continuation must resolve localId 11, not Stan localId 8");
        // Build complete installers; core-only tests once missed a 50-byte overrun.
        var ia=MewBattleCoreInstallerPreset.build(r);var ib=MewEventDataCoreInstallerPreset.build(r);
        require(ia.storedChecksum()==ia.calculatedChecksum() && ib.storedChecksum()==ib.calculatedChecksum(),"installer checksums");
        require(ia.hasWonderCardHeader() && ib.hasWonderCardHeader(),"installer WC headers");
        int split=MewBattleCoreExtension.SCENE_PREFIX_IN_CORE_A;
        byte[] scenes=java.util.Arrays.copyOf(x.bytes(),x.sceneBytesLength());
        require(a.bytes().length==MewBattleCoreExtension.START && split%4==0,"aligned scene boundary");
        require(contains(ia.scriptCopy(),concat(a.bytes(),java.util.Arrays.copyOfRange(scenes,0,split))),"A core plus scene prefix");
        require(contains(ib.scriptCopy(),concat(b.bytes(),java.util.Arrays.copyOfRange(scenes,split,scenes.length))),"B core plus remaining scenes");
        byte[] event=MewFinalEventPreset.build(r).ramScript().scriptCopy();
        require(contains(event,new byte[]{0x79,(byte)0x97,0,10,0,0,0,0,0,0,0,0,0,0,0,0x19,4,(byte)0x80,13,(byte)0x80}),"givemon destination preserved before dispatcher mode");
}private static byte[] concat(byte[]a,byte[]b){byte[]c=java.util.Arrays.copyOf(a,a.length+b.length);System.arraycopy(b,0,c,a.length,b.length);return c;}private static boolean contains(byte[]a,byte[]b){outer:for(int i=0;i<=a.length-b.length;i++){for(int j=0;j<b.length;j++)if(a[i+j]!=b[j])continue outer;return true;}return false;}private static void require(boolean v,String m){if(!v)throw new AssertionError(m);} }
