import java.io.ByteArrayOutputStream;

/* builds the small default ramscript attached to WC3 files created from zero. this is intentionally not a general ramscript 
editor. wc3-builder owns card design/details; ramscript-tools owns arbitrary Field Script editing.

the only purpose of this class is to make "create" produce a usable base WC3 whose deliveryman explains that no real event is 
attached yet. */

final class DefaultDeliveryScript {
    static final int SIZE = 0x3EC;
    static final int CHECKSUM_OFFSET = 0x000;
    static final int DATA_OFFSET = 0x004;
    static final int DATA_SIZE = 1000;
    static final int SCRIPT_OFFSET = 0x008;
    static final int SCRIPT_SIZE = 995;

    private static final long VIRTUAL_BASE = 0x08010000L;

    static final String MESSAGE = "This custom card was generated by\\n" + "Choppy's wc3 builder.\\p" + "It has no event attached.";

    private DefaultDeliveryScript() {}

    static byte[] build() {
        ByteArrayOutputStream script = new ByteArrayOutputStream();

        /* setvaddress VIRTUAL_BASE */
        u8(script, 0xB8);
        u32(script, VIRTUAL_BASE);

        /* lock; faceplayer */
        u8(script, 0x6A);
        u8(script, 0x5A);

        /* vmessage messagePointer */
        u8(script, 0xBD);
        int pointerOffset = script.size();
        u32(script, 0);

        /* waitmessage; waitbuttonpress; release; end */
        u8(script, 0x66);
        u8(script, 0x6D);
        u8(script, 0x6C);
        u8(script, 0x02);

        int messageOffset = script.size();
        byte[] message = Gen3TextCodec.encodeString(MESSAGE);
        script.writeBytes(message);

        byte[] scriptBytes = script.toByteArray();

        long messagePointer = VIRTUAL_BASE + Integer.toUnsignedLong(messageOffset);
        putU32(scriptBytes, pointerOffset, messagePointer);

        if (scriptBytes.length > SCRIPT_SIZE) {
            throw new IllegalStateException(
                    "Default delivery script exceeds RamScript capacity: " + scriptBytes.length
            );
        }

        byte[] ramScript = new byte[SIZE];

        /* struct RamScriptData header used for Wonder Card scripts. */
        ramScript[DATA_OFFSET] = 0x33;
        ramScript[DATA_OFFSET + 1] = (byte) 0xFF;
        ramScript[DATA_OFFSET + 2] = (byte) 0xFF;
        ramScript[DATA_OFFSET + 3] = (byte) 0xFF;

        System.arraycopy(
                scriptBytes,
                0,
                ramScript,
                SCRIPT_OFFSET,
                scriptBytes.length
        );

        int checksum = Crc16.calculate(
                ramScript,
                DATA_OFFSET,
                DATA_SIZE
        );
        Binary.putU32(ramScript, CHECKSUM_OFFSET, checksum);

        return ramScript;
    }

    private static void u8(ByteArrayOutputStream output, int value) {
        output.write(value & 0xFF);
    }

    private static void u32(ByteArrayOutputStream output, long value) {
        output.write((int) value & 0xFF);
        output.write((int) (value >>> 8) & 0xFF);
        output.write((int) (value >>> 16) & 0xFF);
        output.write((int) (value >>> 24) & 0xFF);
    }

    private static void putU32(byte[] data, int offset, long value) {
        data[offset] = (byte) value;
        data[offset + 1] = (byte) (value >>> 8);
        data[offset + 2] = (byte) (value >>> 16);
        data[offset + 3] = (byte) (value >>> 24);
    }
}
